version: "3.8"

services:
  ilpo-bot:
    build: .
    container_name: ilpo-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      # Mount resources directory to persist AI text files
      - ./resources:/app/resources:ro
      # Optional: Mount logs directory
      - ./logs:/app/logs
    networks:
      - ilpo-network
    # Optional: Add memory limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ilpo-network:
    driver: bridge

# Optional: Add volume for persistent data
volumes:
  ilpo-logs:
    driver: local
